default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('PGHOST', 'localhost') %>
  port: <%= ENV.fetch('PGPORT', 5432) %>
  username: <%= ENV.fetch('PGUSER', 'postgres') %>
  password: <%= ENV['PGPASSWORD'] %>
  database: <%= ENV.fetch('PGDATABASE', 'submit_ruby_development') %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch('PGDATABASE', 'submit_ruby_test') %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
